menu:
  about: /about
  archive: /archives

excerpt_link: read more

fancybox: true

per_page: 3

comment:
  enable: true
  disqus_shortname: deubaka

google_analytics: UA-71294425-1

deploy:
  type: heroku
  repo: git@heroku.com:deubaka-hexo-blog.git
